CPP = g++
TARGET = solitario

# all
all: .all-post

.all-post: Carta.o Cola.o Pila.o ControlCartas.o Game.o ListaDoble.o Movimiento.o ListMovment.o Utiles.o main.o
	$(CPP) Carta.o Cola.o Pila.o ControlCartas.o Game.o ListaDoble.o Movimiento.o ListMovment.o Utiles.o main.o -o $(TARGET)


Carta.o: Carta.cpp Carta.h
	$(CPP) -c Carta.cpp

Pila.o: Pila.cpp Pila.h
	$(CPP) -c Pila.cpp

ControlCartas.o: ControlCartas.cpp ControlCartas.h
	$(CPP) -c ControlCartas.cpp

Game.o: Game.cpp Game.h
	$(CPP) -c Game.cpp

ListaDoble.o: ListaDoble.cpp ListaDoble.h
	$(CPP) -c ListaDoble.cpp

Movimiento.o: Movimiento.cpp Movimiento.h
	$(CPP) -c Movimiento.cpp

ListMovment.o: ListMovment.cpp ListMovment.h
	$(CPP) -c ListMovment.cpp

Utiles.o: Utiles.cpp Utiles.h
	$(CPP) -c Utiles.cpp

main.o:
	$(CPP) -c main.cpp

# clean
clean:
	rm -f *.o $(TARGET)